[project]
name = "video-edit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "gradio>=6.0.2",
    "moviepy>=2.2.1",
    "pytest>=9.0.1",
]
